#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.


_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
source \
  "${_lib}/libcrash-bash/crash-bash"

# Check all required programs
# are available
_requirements() {
  _check_cmd \
    "base64" \
    "coreutils"
}

# shellcheck disable=SC2034
_global_variables() {
  make_date=""
  out_txt=""
  in_file=""
  encoding_format=""
  buffer_size=""
  string_length=""
  amount_only=""
  color=""
  quiet=""
}

_chunk_split() {
  local \
    _in="${1}" \
    _length="${2}" \
    _prefix="${3}" \
    _block_last="${4}" \
    _chunks \
    _chunk \
    _total \
    _head \
    _content \
    _cut \
    _out \
    _msg=()
  _total="${#_in}"
  _chunks="$(( \
    "${_chunk_current}" +
    "${_total}" / "${_length}" + 1))"
  if (( "${_chunks}" < 2 )); then
    _out="${_prefix}"
    if [[ "${_block_last}" == "true" ]]; then
      printf \
        "%s" \
        "${_in}" > \
        "${_out}"
    elif [[ "${_block_last}" == "false" ]]; then
      echo \
        "${_in}" > \
	"${_out}"
    fi
    return \
      0
  fi
  _msg=(
    "Chunking ${_total}"
    "letters into '${_chunks}'."
  )
  _msg_info \
    "${_msg[*]}"
  for _chunk \
    in $(seq "$(( "${_chunk_current}" + 1 ))" \
             "${_chunks}"); do
    _chunk_start="$(( \
      _chunk * _length - _length ))"
    _cut="${_in:${_chunk_start}:${_length}}"
    _out="${_prefix}.${_chunk}"
    _msg=(
      "Writing chunk ${_chunk} '${_out}'"
      "of length ${#_cut} out of ${_chunks}."
    )
    _msg_info \
      "${_msg[*]}"
    if (( "${_chunk}" < "${_chunks}" )); then
      printf \
        "%s" \
        "${_cut}" > \
        "${_out}"
    elif [[ "${_chunk}" == "${_chunks}" ]]; then
      if [[ "${_block_last}" == "true" ]]; then
        printf \
          "%s" \
          "${_cut}" > \
          "${_out}"
      elif [[ "${_block_last}" == "false" ]]; then
        echo \
          "${_cut}" > \
          "${_out}"
      fi
    fi
  done
  _chunk_current="${_chunks}"
  _msg=(
    "Finished encoding block."
  )
  _msg_info \
    "${_msg[*]}"
}

_blocks_find() {
  local \
    _pattern="${1}" \
    _pkgname=() \
    _find_opts=()
  shift \
    1
  _msg=(
    "Looking for blocks with pattern"
    "'${_pattern}'."
  )
  _msg_info \
    "${_msg[*]}"
  _find_opts+=(
    -type
      "f"
    -print0
  )
  _msg=(
    "Running find with options"
    "'${_find_opts[@]}'."
  )
  _msg_info \
    "${_msg[*]}"
  mapfile \
    -d \
    $'\0' \
    _blocks < \
    <(find \
        "${_pattern}"* \
        "${_find_opts[@]}" 2>/dev/null || \
      true)
}

_buffer_prepare() {
  local \
    _in="${1}" \
    _out="${2}" \
    _buffer_size_bytes="${3}" \
    _in_size_bytes \
    _split_opts=() \
    _msg=()
  _in_size_bytes="$( \
    du \
      -bs \
      "${_in}" | \
      awk \
        '{print $1}')"
  _msg=(
    "File '${_in}' has size"
    "'${_in_size_bytes}' bytes."
  )
  _msg_info \
    "${_msg[*]}"
  _blocks_total="$(( \
    _in_size_bytes / _buffer_size_bytes + 1))"
  split \
    -n \
      "l/${_blocks_total}" \
    --numeric-suffixes="1" \
    "${_in}" \
    "${_out}.block."
  _blocks_find \
    "${_out}.block"
}

_base64_encode() {
  local \
    _block="${1}" \
    _length="${2}" \
    _block_last="${3}" \
    _txt \
    _msg=()
  read \
    -rd \
      '' \
    _txt < \
    <(base64 \
        --wrap=0 \
        "${_block}") || \
    true
  _msg=(
    "Block '${_block}' encoded,"
    "length: ${#_txt}."
  )
  _msg_info \
    "${_msg[*]}"
  if [[ "${_amount_only}" == "n" ]]; then
    _chunk_split \
      "${_txt}" \
      "${_length}" \
      "${_out}" \
      "${_block_last}"
  elif [[ "${_amount_only}" == "y" ]]; then
    _txt_chunks_total="$(( \
      "${_total_txt_chunks}" + \
      "${#_txt}" / "${_length}" + \
      1 ))"
  fi
  _msg=(
    "Finished encoding block"
    "'${_block}'."
  )
  _msg_info \
    "${_msg[*]}"
}

_bin2txt() {
  local \
    _in="${1}" \
    _out="${2}" \
    _format="${3}" \
    _length="${4}" \
    _buffer_size_bytes="${5}" \
    _amount_only="${6}" \
    _blocks=() \
    _blocks_total \
    _txt_chunks_total \
    _chunk_current \
    _block_current \
    _block_last \
    _msg=()
  _buffer_prepare \
    "${_in}" \
    "${_out}" \
    "${_buffer_size_bytes}"
  _chunk_current="0"
  _block_current="1"
  for _block in \
    "${_blocks[@]}"; do
    _msg=(
      "Reading block '${_block_current}'" 
      "of '${_blocks_total}'."
    )
    _msg_info \
      "${_msg[*]}"
    if (( "${_block_current}" < "${_blocks_total}" )); then
      _block_last="false"
    elif [[ "${_block_current}" == "${_blocks_total}" ]]; then
      _block_last="true"
    fi
    "_${_format}_encode" \
      "${_block}" \
      "${_length}" \
      "${_block_last}"
    _block_current="$(( \
      _block_current + 1))"
  done
  rm \
    -rf \
    "${_blocks[@]}"
  if [[ "${_amount_only}" == "y" ]]; then
    echo \
      "${_txt_chunks_total}"
  elif [[ "${_amount_only}" == "n" ]]; then
    _msg=(
      "Finished '${_format}' encoding"
      "input file '${_in}'."
    )
    _msg_info \
      "${_msg[*]}"
  fi
}

# Set defaults and, if present, overrides
# from arch-grub command line option parameters
_set_overrides() {
  _set_override \
    "make" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "encoding" \
    "format" \
    "base64"
  _set_override \
    "in" \
    "file" \
    ""
  _set_override \
    "out" \
    "txt" \
    ""
  _set_override \
    "string" \
    "length" \
    "10000"
  _set_override \
    "buffer" \
    "size" \
    "2000000" # 2MB
  _set_override \
    "amount" \
    "only" \
    "n"
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "                Make date:   ${make_date}"
  _msg_info "          Encoding format:   ${encoding_format}"
  _msg_info "              Buffer size:   ${buffer_size}"
  _msg_info "      Chunk string length:   ${string_length}"
  _msg_info "       Chunks amount only:   ${amount_only}"
  _msg_info "                  In file:   ${in_file}"
  _msg_info "            Out text file:   ${out_txt}"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Converts binary to ascii text.

Usage:
  $(_get "app" "name")
    [options]
    <in_file>
    <out_txt>
  options:
     -f <encoding_format> Encoding format ('base64').
                          Default: '${encoding_format}'
     -B <buffer_size>     Size in bytes the input file will
                          be split before being read
			  in memory and passed to
			  the encoder.
			  Default: '${buffer_size}'
     -L <string_length>   String chunk length.
			  Default: '${string_length}'
     -s                   Only print chunks amount.
                          Default: '${amount_only}'


     -h                   This message.
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'f:L:scvh?' \
    arg; do
  case \
    "${arg}" in
    f) override_encoding_format="${OPTARG}" ;;
    L) override_string_length="${OPTARG}" ;;
    s) override_amount_only="y" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
	 _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0 && \
    _set_overrides && \
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
_set_overrides
_required_args=2
if [[ "$(_get "amount" "only")" == "y" ]]; then
  _required_args=1
fi
(( $# < "${_required_args}" )) && \
  _msg_error \
    "missing arguments" \
    0 && \
  _usage \
    1
_set \
  "in" \
  "file" \
  "${1}"
if (( 1 < $# )); then
  _set \
    "out" \
    "txt" \
    "${2}"
fi
_show_config
app_opts=(
  "${in_file}"
  "${out_txt}"
  "${encoding_format}"
  "${string_length}"
  "${buffer_size}"
  "${amount_only}"
)
_bin2txt \
  "${app_opts[@]}"
