#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
        "env")")"
_lib="$( \
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" 2>/dev/null || \
  source \
    "${_crash_bash}"

# Check all required programs
# are available
_requirements() {
  _check_cmd \
    "base64" \
    "coreutils"
  _check_cmd \
    "cat" \
    "coreutils"
}

# shellcheck disable=SC2034
_global_variables() {
  make_date=""
  out_file=""
  encoding_format=""
  argument_type=""
  in_texts=()
  color=""
  quiet=""
}

_assemble() {
  local \
    _out="${1}" \
    _in=() \
    _file \
    _data \
    _msg=()
  shift \
    1
  _in+=(
    "$@"
  )
  if [[ "${_argument_type}" == "list" ]]; then
    _msg=(
      "Merging files from list at"
      "'${_list}' into '${_out}'."
    )
  elif [[ "${_argument_type}" == "file" ]]; then
    _msg=(
      "Merging '${_in[*]}' into '${_out}'."
    )
  fi
  _msg_info \
    "${_msg[*]}"
  for _file \
    in "${_in[@]}"; do
    IFS= \
    read \
      -rd \
        '' \
      _data < \
      <( cat \
           "${_file}") || \
      true
    printf \
      "%s" \
      "${_data}" >> \
      "${_out}"
  done
  _msg_info \
    "Merging finished."
}

_base64_decode() {
  local \
    _out="${1}" \
    _in=() \
    _file \
    _data \
    _txt
  shift \
    1
  _in+=(
    "$@"
  )
  _txt="${_in}"
  if (( 1 < "${#_in[@]}" )); then
    _txt="$( \
      mktemp \
        --suffix=".base64")"
    _assemble \
      "${_txt}" \
      "${_in[@]}"
  fi
  _msg=(
    "Decoding ${_txt} into ${_out}."
  )
  _msg_info \
    "${_msg[*]}"
  ( base64 \
      -d \
      "${_txt}" > \
      "${_out}" ) || \
  ( _msg=(
      "Decoding failed."
    )
    _msg_error \
      "${_msg[*]}" )
  if [[ "${_txt}" != "${_in}" ]]; then
    rm \
      "${_txt}"
  fi
  _msg_info \
    "decoding finished"

}

_txt2bin() {
  local \
    _out="${1}" \
    _format="${2}" \
    _argument_type="${3}" \
    _in=() \
    _list
  shift \
    3
  _in+=(
    "$@"
  )
  if [[ "${_argument_type}" == "list" ]]; then
    _list="${_in[0]}"
    _in=( $( \
      cat \
        "${_in[0]}")
    )
  fi
  "_${_format}_decode" \
    "${_out}" \
    "${_in[@]}"
}

# Set defaults and, if present, overrides
# from arch-grub command line option parameters
_set_overrides() {
  _set_override \
    "make" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "encoding" \
    "format" \
    "base64"
  _set_override \
    "argument" \
    "type" \
    "file"
  _set_override \
    "out" \
    "file" \
    ""
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "                Make date:   ${make_date}"
  _msg_info "            Argument type:   ${argument_type}"
  _msg_info "          Encoding format:   ${encoding_format}"
  _msg_info "                 Out file:   ${out_file}"
  _msg_info "       Input text file(s):   ${in_texts[*]}"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Converts text to binary.

Usage:
  ${app_name}
    [options]
    <out_file>
    [in_text]

  options:
     -t <argument_type>   Possible values are 'file' and
                          'list'.
                          When it is 'file' the arguments
			  are the encoded file paths,
                          when it is 'list' the argument is
                          a file containing the paths of the
                          encoded files.
                          Default: '${argument_type}'
     -f <encoding_format> Encoding format ('base64').
                          Default: '${encoding_format}'

     -h                   This message.
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    't:f:cvh?' \
    arg; do
  case \
    "${arg}" in
    t) override_argument_type="${OPTARG}" ;;
    f) override_encoding_format="${OPTARG}" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
	 _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'." \
      0 && \
    _set_overrides && \
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
(( $# < 2 )) && \
  _msg_error \
    "Missing arguments." \
    0 && \
  _set_overrides && \
  _usage \
    1
out_file="${1}"
shift \
  1
in_texts+=(
  "$@"
)
_set_overrides
_show_config
app_opts=(
  "${out_file}"
  "${encoding_format}"
  "${argument_type}"
  "${in_texts[@]}"
)
_txt2bin \
  "${app_opts[@]}"
